//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monamedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int reviewID { get; set; }
        public Nullable<int> orderDetailID { get; set; }
        public Nullable<int> star { get; set; }
        public string cmtCustomer { get; set; }
        public string cmtStaff { get; set; }
        public Nullable<System.DateTime> cmtTime { get; set; }
    
        public virtual orderDetail orderDetail { get; set; }
    }
}
